create_test_zimfiles creates smaller ZIM files
Before this fix test/data/small.zim (as well as each of all but one
broken ZIM files derived from it) weighed 78KiB while the source data
was under 4KiB. Generating the source ZIM file without the full-text
xapian index saves us 32KiB in each of those test ZIM files.
Unfortunately the title/xapian index (measuring ~40KiB) still remains.

Also fixed the metadata of test/data/small.zim (before this commit all
of metadata passed on the command line was prefixed with a '='
character).

No ZIM file is regenerated at this point. This commit is made just as a
side improvement before the next commit, where `create_test_zimfiles`
will be modified too.

diff --git a/test/data/create_test_zimfiles b/test/data/create_test_zimfiles
--- a/test/data/create_test_zimfiles
+++ b/test/data/create_test_zimfiles
@@ -4,7 +4,7 @@ myname=$(basename "$0")
 
 die()
 {
-  echo >&2 '!!! ERROR: $*'
+  echo >&2 "!!! ERROR: $*"
   exit 1
 }
 
@@ -38,13 +38,14 @@ cd "$(dirname "$0")"
 if [ "$mode" == '--all' ]
 then
   rm -f small.zim
-  zimwriterfs -w main.html \
+  zimwriterfs --withoutFTIndex \
+              -w main.html \
               -f favicon.png \
-              -l=en \
-              -t="Test ZIM file" \
-              -d="" \
-              -c="" \
-              -p="" \
+              -l en \
+              -t "Test ZIM file" \
+              -d "N/A" \
+              -c "N/A" \
+              -p "N/A" \
               small_zimfile_data \
               small.zim \
   && echo 'small.zim was successfully created' \
